apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threads-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    # ðŸ’¡ ESTA ANNOTATION ES CLAVE: Necesaria para el backend
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
spec:
  tls:
  - hosts:
    - threads.inf326.nursoft.dev
    secretName: threads-tls-secret
  rules:
    - host: threads.inf326.nursoft.dev
      http: 
        paths:
          # 1. REGLA PARA EL BACKEND (API)
          - path: /threads(/|$)(.*) # <--- La API se moverÃ¡ a /threads
            pathType: Prefix
            backend:
              service:
                name:  threads-api-service
                port:
                  number: 80
          
          # 2. REGLA PARA EL FRONTEND (RAÃZ)
          - path: / # <--- La raÃ­z ahora es para el frontend
            pathType: Prefix
            backend:
              service:
                name: threads-frontend-service # <--- Â¡Nuevo Service!
                port:
                  number: 80
            