apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threads-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
  - hosts:
    - threads.inf326.nursoft.dev
    secretName: threads-tls-secret
  rules:
    - host: threads.inf326.nursoft.dev
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  threads-api-service
                port:
                  number: 80