apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: threads-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # Apunta a tu 'threads-deployment'
    name: threads-deployment
  minReplicas: 1
  maxReplicas: 5 # MÃ¡ximo 5 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # Si el CPU supera el 80%, crea un pod nuevo
          averageUtilization: 80
