apiVersion: apps/v1
kind: Deployment
metadata:
  name: threads-deployment
spec:
  # üîΩ ¬°SIMPLIFICADO!
  replicas: 1
  selector:
    matchLabels:
      app: threads
  template:
    metadata:
      labels:
        app: threads
    spec:
      containers:
        - name: threads
          # ‚ö†Ô∏è Pon tu imagen correcta aqu√≠
          image: flaviooyarce/t4-arqui-software:v1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://threads:threads@db:5432/threads"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
            - name: SERVICE_NAME
              value: "threads"
            - name: EVENT_EXCHANGE
              value: "platform.events"
            - name: EVENT_VERSION
              value: "1"
            - name: CHANNEL_EVENT_QUEUE
              value: "threads.channel.events"
            - name: ENABLE_EVENTS
              value: "true"
            - name: ALLOWED_ORIGINS
              value: "*"
