apiVersion: v1
kind: Service
metadata:
  name: threads-service
spec:
  type: LoadBalancer # ğŸ‘ˆ Esto crea la URL pÃºblica
  ports:
    - port: 80 # Puerto pÃºblico
      targetPort: 8000 # Puerto de tu app
  selector:
    app: threads
