apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer

    # ðŸ’¡ Annotations de reescritura solo para esta ruta
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - threads.inf326.nursoft.dev
      secretName: threads-tls-secret
  rules:
    - host: threads.inf326.nursoft.dev
      http:
        paths:
          # Esta regla SÃ“LO aplica para /index
          - path: /index
            pathType: Prefix
            backend:
              service:
                name: threads-frontend-service
                port:
                  number: 80
